name: Wolfboot Reusable Build Workflow

on:

  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config-file:
        required: true
        type: string
      make-args:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Workaround for sources.list
        run: |
            # workaround disabled, splitting the load between azure and arizona.edu to avoid timeouts

            # See reference code in test-build.yml for various sources that may be updated. Enable as needed here.
            echo "Workaround for sources.list disabled for this workflow"

      - name: Update repository
        run: sudo apt-get update

      - name: Install cross compilers
        run: |
          sudo apt-get install -y gcc-arm-none-eabi gcc-aarch64-linux-gnu gcc-powerpc-linux-gnu gnu-efi

      - name: make clean
        run: |
          make distclean

      - name: Select config
        run: |
          cp ${{inputs.config-file}} .config

      - name: Build tools
        run: |
          make -C tools/keytools && make -C tools/bin-assemble

      - name: Build wolfboot
        run: |
          make ${{inputs.make-args}}
